[general]
# Directories to search for templates, relative to the crate root.
dirs = [ "src/bindings/kotlin/templates", "src/bindings/python/templates",  ]

[[syntax]]
name = "kt"

[[syntax]]
name = "py"

[[syntax]]
name = "swift"
