# Build all the things we need for CI

version: 2.1

commands:
  make_install_uniffi_bindgen:
    steps:
      - run:
          name: Build and install uniffi-bindgen
          command: cargo install --path uniffi_bindgen
jobs:
  Check Rust formatting:
    docker:
      - image: circleci/rust:latest
    resource_class: small
    steps:
      - checkout
      - run: rustup component add rustfmt
      - run: rustfmt --version
      - run: cargo fmt -- --check
  Lint Rust with clippy:
    docker:
      - image: circleci/rust:latest
    resource_class: small
    steps:
      - checkout
      - run: rustup component add clippy
      - make_install_uniffi_bindgen
      - run: cargo clippy --version
      - run: cargo clippy --all --all-targets
  Rust and Foreign Language tests:
    docker:
      - image: rfkelly/uniffi-ci:latest
    resource_class: medium
    steps:
      - run: cat ~/.profile >> $BASH_ENV
      - checkout
      - make_install_uniffi_bindgen
      - run: cargo test

workflows:
  version: 2
  check-formatting:
    jobs:
      - Check Rust formatting
  clippy:
    jobs:
      - Lint Rust with clippy
  run-tests:
    jobs:
      - Rust and Foreign Language tests
