[package]
name = "uniffi"
version = "0.1.0"
authors = ["Firefox Sync Team <sync-team@mozilla.com>"]
license = "MPL-2.0"
edition = "2018"

[dependencies]
# Re-exported dependencies used in generated Rust scaffolding files.
anyhow = "1"
bytes = "0.5"
ffi-support = "0.4"
lazy_static = "1.4"
log = "0.4"
# Regular dependencies
cargo_metadata = "0.11"
uniffi_bindgen = { path = "../uniffi_bindgen", optional = true }

[features]
default = []
builtin-bindgen = ["uniffi_bindgen"]
