[package]
name = "uniffi_build"
version = "0.1.0"
authors = ["Firefox Sync Team <sync-team@mozilla.com>"]
license = "MPL-2.0"
edition = "2018"

[dependencies]
cargo_metadata = "0.11"
anyhow = "1"
uniffi_bindgen = { path = "../uniffi_bindgen", optional = true }

[features]
default = []
builtin-bindgen = ["uniffi_bindgen"]
