# [bindings.kotlin]
# package_name = "org.mozilla.uniffi.example.arithmetic"
# cdylib_name = "arithmetical" TODO: BRING THIS BACK BEFORE MERGE

# [bindings.python]
# cdylib_name = "arithmetical"

# [bindings.ruby]
# cdylib_name = "arithmetical"

# [bindings.swift]
# cdylib_name = "arithmetical"
